name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2  # Versión actualizada
        with:
          path: './'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2